# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-28 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('managTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 9, 28, 6, 37, 33, 826146, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
    ]
